# Generated by Django 4.1 on 2024-05-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("air_condition", "0002_rename_wind_speed_room_fan_speed_alter_room_room_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Server",),
    ]
